#!/usr/bin/env sh

sticker=$(rmpc sticker get "$FILE" "playCount" | grep -oP '"value":"\K[^"]+')
if [ -z "$sticker" ]; then
  rmpc sticker set "$FILE" "playCount" "1"
else
  rmpc sticker set "$FILE" "playCount" "$((sticker + 1))"
fi
